name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: csharp/Microsoft.Azure.Databricks.Client.sln
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    
    - name: Restore
      run: dotnet restore $env:Solution_Name
        
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }} $env:Solution_Name

    - name: Test
      run: dotnet test --no-restore $env:Solution_Name
    
