name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: csharp/Microsoft.Azure.Databricks.Client.sln
    
    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: |
          9.x
          8.x
    
    - name: Restore
      run: dotnet restore "$Solution_Name"
        
    - name: Build
      run: dotnet build --no-restore --configuration Release "$Solution_Name"

    - name: Test
      run: dotnet test "$Solution_Name" --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Package
      run: dotnet pack "$Solution_Name" --no-build --configuration Release --verbosity Detailed

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 75'
    
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
          name: artifacts
          path: |
            code-coverage-results.md
            **/bin/**
