name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: csharp/Microsoft.Azure.Databricks.Client.sln
    
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: |
          9.x
          8.x
    
    - name: Restore
      run: dotnet restore "$Solution_Name"
        
    - name: Build
      run: dotnet build --no-restore --configuration Release "$Solution_Name"

    - name: Test
      run: dotnet test "$Solution_Name" --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Package
      run: dotnet pack "$Solution_Name" --no-build --configuration Release --verbosity Detailed

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 75'
    
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
          name: artifacts
          path: |
            code-coverage-results.md
            **/bin/**
